config/routes.rb
GiantRiver::Application.routes.draw do
  get "reviews/index"
  get "reviews/new"
  get "reviews/edit"
  get "reviews/show"
  get "sessions/new"
  resources :products do
  resources :reviews 
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy] 

  root 'products#index'

  

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reviews
  has_many :users, :through => :reviews

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f/100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
 class Review < ActiveRecord::Base
  validates :content, :presence => true
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews
  has_many :products, :through => :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_filter :ensure_logged_in, :only => [:show]
  
  def index
    @products = Product.order('products.created_at DESC').page(params[:page])

    if params[:term]
      @products = @products.where('name LIKE ?', "%#{params[:term]}%")
    end

    respond_to do |format|
      format.js
      format.html
      format.json { render json: @products } 
    end
    #@products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def new
    @review = Review.new
  end


  def show
    @review = Review.find(params[:id])
  end

  def create

    @review = Review.new( 
      :content => params[:review][:content],
      :product_id => @product.id,
      :user_id => current_user.id
      ) 

  #   if @review.save
  #     redirect_to product_path(@product), notice: 'Review created successfully'
  #   else
  #     render :action => :show
  #   end
  # end
    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: 'Review added.' }
        format.js {} # This will look for /views/reviews/create.js.erb
      else
        format.html { render "products/show", notice: 'There was an error.'  }
        format.js {} # This will look for /views/reviews/create.js.erb
      end
    end    
end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  def edit
    @review = Review.find(params[:id])
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to users_path
      else
        render :new
      end
  end

  def edit
    @user = User.find(user_params)
  end

  def show
  end

  def index
    @user = User.all
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "The Amazon" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>

       <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>

  </body>
</html>

app/views/products/_error.html.erb
 <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

app/views/products/_form.html.erb
<%= form_for (@product) do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  
  <div class = "field">
    <%= f.label :name %> <br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %> <br />
    <%= f.text_area :description %><br />
  </div>

  <div class= "field">
    <%= f.label :price_in_cents %> <br />
    <%= f.number_field :price_in_cents %><br />
  </div>

  <div class= "actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<ul>
  <%# @products.each do |product| %>

  <li><%= link_to product[:name], "/products/#{product[:id]}" %>  $<%= product.formatted_price %></li>
  <%# end %>
</ul>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
  <% @review.errors.full_messages.each do |error| %>
    <div class="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
    <p>
      <%= review.content %>
      <br>
      <% if review.user != nil %>
      <em> by <%= review.user.name %></em>
      Added on: <%= review.created_at %>
    <% else %>
      <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
    <% end %>
  <% end %>

app/views/products/edit.html.erb
<h1>Edit a product</h1>

<p>
  <%= link_to "Back to products", "/products/index" %>
</p>

<%= render "form" %>




<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<%= link_to "Add a product", new_product_path %>

<h1>Products</h1>

<hr />

<div id="product_search">
<%= label_tag :term, "Find a product:" %>
<%= text_field_tag :term %>
</div>

<hr /> 

<div id="products">
  <%= render @products %>
</div>

<%= paginate @products %>

app/views/products/index.js.erb
$('#products').append('<%= j render(@products) %>');
$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<h1>Add a product</h1>

<p>
  <%= link_to "Back to products", "/products/index" %>
</p>

<%= render "form" %>




<p>Find me in app/views/products/new.html.erb</p>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<%= link_to "Back to products", products_url %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %>

<p><%=@product[:name] %>, <%= @product.formatted_price %></p>

<p><%=@product[:description] %></p>

<h3>Reviews</h3>

<p>Review for <%= @product.name %></p>
  <div id="review-list"> 
      <%= render :partial => "products/reviews" %>
</div>

  <h4>New Review</h4>

  <%= form_for([@product, @review], :remote => true) do |f| %>

  <div id="review-form-errors">
    <%= render :partial => "/products/review_form_errors" %>
  </div>

    <div class="field">
      <%= f.label "Comment:" %><br />
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", :id => "new_review" %>
    </div>
  <% end %>


<script type="text/javascript">

//   $(document).ready(function() {
//      $("#new_review")
//         .on('ajax:beforeSend', function() {alert("loading!");})
//         .on('ajax:success', function(data, status, xhr) {alert("success!");})
//         .on('ajax:error', function(xhr, status, error) {alert("error!");})
//         .on('ajax:complete', function() {alert("complete!");});
//   });

// </script>

<script type="text/javascript">
  $(function() {
     $("#new_review")
        .on('ajax:beforeSend', function(){
          $("input[type='submit']")
            .val('Saving...')
            .attr('disabled', 'disabled'); 
        })
        .on('ajax:complete', function () {
          $("input[type='submit']")
          .val('Submit')
          .removeAttr('disabled');
      });
  });
</script>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label "User Name:" %>
  <%= f.text_field :name %><br/>

  <%= f.label "E-mail:" %>
  <%= f.email_field :email %><br/>
  
  <%= f.label "Password:" %>
  <%= f.password_field :password %><br/>
  
  <%= f.label "Password Confirmation:" %>
  <%= f.password_field :password_confirmation %><br/>

  <%= f.submit "Submit" %>

    <% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

 <%= render "form" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

  <%= render "form" %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>